### ISSUE TITLE
libPYNotation was build in ELF can you provide Mach-O build which used in Mac-os

### ISSUE THREAD

**Issue by yikza** [bullsoft/php-pinyin#3]
libPYNotation was build in ELF which is not loadable in Mac OS  , because the binary format used in Mac OS X is Mach-O , can you provide Mach-O build.
thank you for you support.

**Comment by guweigang** [comment]
Sorry, we have no Mach-O build...

**Comment by ideal** [comment]
Hi, because we only have binary form of libPYNotation, so we can not provide its build for Mac OS X now.
Sorry.
