### ISSUE TITLE
how can we place the pinyin on top of the chinese characters?

### ISSUE THREAD

**Issue by firecentaur** [bullsoft/php-pinyin#4]
is there a way to associate each pinyin with each chinese character? If so, we could then place the text above the chinese characters for easy learning.

**Comment by ideal** [comment]
@firecentaur With bullsoft/php-pinyin you need extra steps to achieve this. However there are many other better solutions: https://github.com/overtrue/pinyin (PHP) , https://github.com/hotoo/pinyin (JavsScript).

**Comment by guweigang** [comment]
You can do some simple jobs to get 2 arrays  which contains pure pinyin and pure chinese characters.
```php
>>> explode("'", "chong'qing'zhong'liang")
=> [
     "chong",
     "qing",
     "zhong",
     "liang",
   ]
>>> $ch = mb_str_split("重庆重量")
=> [
     "重",
     "庆",
     "重",
     "量",
   ]
```

And then, what needed to do is printing them in some way following these steps:
1. printf one pinyin with width 8
2. goto next line
3. print one character with width 8
4. back to previous line and do step 1
